Adapt test to spring boot test current syntax
Also remove

     <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>4.2.8.RELEASE</version>
        </dependency>

which fails test with

```
java.lang.AbstractMethodError: Receiver class org.springframework.context.annotation.AnnotationConfigApplicationContext does not define or inherit an implementation of the resolved method 'abstract org.springframework.beans.factory.ObjectProvider getBeanProvider(java.lang.Class)' of interface org.springframework.beans.factory.BeanFactory
```